
services:
  graphdb:
      image: ontotext/graphdb:10.8.4
      container_name: graphdb
      ports:
        - "7200:7200"
      environment:
        - GRAPHDB_HOME=/opt/graphdb/home
        - GRAPHDB_MIN_DISK_SPACE_MB=50
        - JAVA_OPTS=-Dgraphdb.workbench.maxUploadSize=5000000

      volumes:
        - graphdb-data:/opt/graphdb/home
      restart: unless-stopped

  django:
    build: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - graphdb
    environment:
      - DJANGO_SETTINGS_MODULE=NBAProject.settings

volumes:
  graphdb-data:
      